apiVersion: batch/v1
kind: Job
metadata:
  name: qsharp-job
spec:
  template:
    metadata:
      name: qsharp
    spec:
      containers:
      - name: qsharp
        image: elijun831/qsharp:quantum
        command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
      restartPolicy: Never
